export class DonationsResponse {
  campaign: object; // Consider creating a Campaign type/class
  donor: object; // Consider creating a Donor type/class
  amount: string;
  formatted_amount: string;
  converted_amount: string;
  formatted_converted_amount: string;
  converted_net_amount: string;
  formatted_converted_net_amount: string;
  net_amount: string;
  net_amount_currency: string;
  formatted_net_amount: string;
  recurring: boolean;
  first_recurring_donation: boolean;
  amount_refunded: string;
  formatted_amount_refunded: string;
  stripe_charge_id: string;
  internal_notes: string | null;
  membership_tier: string | null;
  id: number;
  status: string;
  donation_type: string;
  donation_date: string;
  anonymous_donation: boolean;
  gift_aid: boolean;
  designation: string | null;
  join_mailing_list: boolean;
  comment: string | null;
  donating_company: string | null;
  currency: string;
  converted_currency: string;
  offline: boolean;
  utm_campaign: string | null;
  utm_source: string | null;
  utm_medium: string | null;
  utm_term: string | null;
  utm_content: string | null;
  address: string;
  address_line_2: string;
  city: string;
  state: string;
  zip_code: string;
  country: string;
  phone: string | null;
  employer: string | null;
  occupation: string | null;
  processing_fee: number;
  formatted_processing_fee: string;
  fee_covered: boolean;
  cover_fee_amount: number;
  formatted_cover_fee_amount: string;
  app_fee: number;
  formatted_app_fee: string;
  converted_app_fee: number;
  formatted_converted_app_fee: string;
  questions: any[];
  plan_id: number;
  interval: string;

  constructor(data: Partial<DonationsResponse> = {}) {
    this.campaign = data.campaign ?? {};
    this.donor = data.donor ?? {};
    this.amount = data.amount ?? '0';
    this.formatted_amount = data.formatted_amount ?? '$0';
    this.converted_amount = data.converted_amount ?? '0';
    this.formatted_converted_amount = data.formatted_converted_amount ?? '$0';
    this.converted_net_amount = data.converted_net_amount ?? '0';
    this.formatted_converted_net_amount = data.formatted_converted_net_amount ?? '$0';
    this.net_amount = data.net_amount ?? '0';
    this.net_amount_currency = data.net_amount_currency ?? 'USD';
    this.formatted_net_amount = data.formatted_net_amount ?? '$0';
    this.recurring = data.recurring ?? false;
    this.first_recurring_donation = data.first_recurring_donation ?? false;
    this.amount_refunded = data.amount_refunded ?? '0.0';
    this.formatted_amount_refunded = data.formatted_amount_refunded ?? '';
    this.stripe_charge_id = data.stripe_charge_id ?? '';
    this.internal_notes = data.internal_notes ?? null;
    this.membership_tier = data.membership_tier ?? null;
    this.id = data.id ?? 0;
    this.status = data.status ?? '';
    this.donation_type = data.donation_type ?? '';
    this.donation_date = data.donation_date ?? '';
    this.anonymous_donation = data.anonymous_donation ?? false;
    this.gift_aid = data.gift_aid ?? false;
    this.designation = data.designation ?? null;
    this.join_mailing_list = data.join_mailing_list ?? false;
    this.comment = data.comment ?? null;
    this.donating_company = data.donating_company ?? null;
    this.currency = data.currency ?? 'USD';
    this.converted_currency = data.converted_currency ?? 'USD';
    this.offline = data.offline ?? false;
    this.utm_campaign = data.utm_campaign ?? null;
    this.utm_source = data.utm_source ?? null;
    this.utm_medium = data.utm_medium ?? null;
    this.utm_term = data.utm_term ?? null;
    this.utm_content = data.utm_content ?? null;
    this.address = data.address ?? '';
    this.address_line_2 = data.address_line_2 ?? '';
    this.city = data.city ?? '';
    this.state = data.state ?? '';
    this.zip_code = data.zip_code ?? '';
    this.country = data.country ?? '';
    this.phone = data.phone ?? null;
    this.employer = data.employer ?? null;
    this.occupation = data.occupation ?? null;
    this.processing_fee = data.processing_fee ?? 0;
    this.formatted_processing_fee = data.formatted_processing_fee ?? '$0';
    this.fee_covered = data.fee_covered ?? false;
    this.cover_fee_amount = data.cover_fee_amount ?? 0;
    this.formatted_cover_fee_amount = data.formatted_cover_fee_amount ?? '$0';
    this.app_fee = data.app_fee ?? 0;
    this.formatted_app_fee = data.formatted_app_fee ?? '$0';
    this.converted_app_fee = data.converted_app_fee ?? 0;
    this.formatted_converted_app_fee = data.formatted_converted_app_fee ?? '$0';
    this.questions = data.questions ?? [];
    this.plan_id = data.plan_id ?? 0;
    this.interval = data.interval ?? '';
  }
}
